name: Build and Deploy

on:
  push:
    paths:
      - ".github/**"
      - "public/**"
      - "src/**"
      - "package.json"
      - "tsconfig.json"
  workflow_dispatch:

jobs:
  build:
    name: yarn build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Upload built files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/
  deploy:
    name: Deploy to GitHub Pages
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
