name: Build

on:
  push:
    paths:
      - ".github/**"
      - "public/**"
      - "src/**"
      - "package.json"
      - "tsconfig.json"

jobs:
  build:
    name: yarn build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build:prod # will run `yarn build:prod` command
